[package]
name = "hublab-service-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Network Service for HubLab IO"

[dependencies]
