[package]
name = "hublab-service-system"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "System Service for HubLab IO"

[dependencies]
