[package]
name = "hublab-service-update"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "OTA Update Service for HubLab IO"

[dependencies]
serde.workspace = true
sha2.workspace = true
