[package]
name = "hublab-tools-dev"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Developer Tools for HubLab IO"

[dependencies]
serde.workspace = true
