[package]
name = "hublab-apps-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Core Applications for HubLab IO"

[dependencies]
